### ISSUE TITLE
make failed -  No rule to make target `src/arch/riscv/halt.o'

### ISSUE THREAD

**Issue by crolfes** [heshamelmatary/seL4-riscv-mk#1]
When following the [HOWTO] Build and run seL4 on RISC-V targets the make command fails with the error message:

```
[apps/sos] done.
[KERNEL]
 [MKDIR] arch/object
 [PBF_GEN] arch/object/structures.pbf
 [PBF_GEN] plat/machine/hardware.pbf
 [PBF_GEN] api/types.pbf
 [BF_GEN] arch/object/structures_gen.h
 [BF_GEN] plat/machine/hardware_gen.h
 [BF_GEN] api/types_gen.h
 [CPP] src/arch/riscv/head.s
 [AS] src/arch/riscv/head.o
make[1]: *** No rule to make target `src/arch/riscv/halt.o', needed by `kernel.elf'.  Stop.
make: *** [kernel_elf] Error 2
```

When executing make a second time following error message shows up:

```
/home/lowrisc/seL4riscv/kernel/src/plat/spike/machine/io.c: In function 'halt':
/home/lowrisc/seL4riscv/kernel/src/plat/spike/machine/io.c:121:1: warning: 'noreturn' function does return
 }
 ^
 [AS] kernel.o
/home/lowrisc/seL4riscv/kernel/src/plat/spike/machine/hardware.c: Assembler messages:
/home/lowrisc/seL4riscv/kernel/src/plat/spike/machine/hardware.c:108: Error: Instruction csrw requires absolute expression
/home/lowrisc/seL4riscv/kernel/src/plat/spike/machine/hardware.c:119: Error: Instruction csrw requires absolute expression
make[1]: *** [kernel.o] Error 1
make: *** [kernel_elf] Error 2
```

**Comment by heshamelmatary** [comment]
I suspect the first error is because of running make with -j option.

The other error is a known issue [1] part of the timer handling code. The current seL4 code follows the 1.7 RISC-V spec [2], and was compiling fine before this riscv-gnu-toolchain commit https://github.com/riscv/riscv-gnu-toolchain/commit/b85637e5d20e84c263a134f329e09d081714b983 
but then there have been RISC-V changes that break the current timer code and are not documented. These changes will be released in the next 1.8 spec, and I preferred to wait till then.

For now you have two solutions:

1) I've commented the timer code in the kernel, so you may just run "repo sync" from the seL4 root directory, or "git pull" from the kernel directory, and then build again. That's in case you don't need timer operations.

2) Otherwise, you may revert back to an older revision of riscv-gnu-toolchain before this change https://github.com/riscv/riscv-gnu-toolchain/commit/b85637e5d20e84c263a134f329e09d081714b983 happened, and build the toolchain again.

[1] https://github.com/riscv/riscv-gnu-toolchain/issues/79
[2] http://riscv.org/download.html#tab_spec_privileged_isa
